name: ci

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read
  pull-requests: write

env:
  REPOSITORY: judedaryl/hello-world

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.sha.outputs.short_sha }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Generate short sha
      id: sha
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "short_sha=$calculatedSha" >> "$GITHUB_OUTPUT"  

  build_and_publish:
    runs-on: ubuntu-latest
    needs: 
    - setup
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
            
    - name: Build
      uses: docker/build-push-action@v6
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          ${{ env.REPOSITORY }}:${{ needs.setup.outputs.short_sha }}
          ${{ env.REPOSITORY }}:latest        